spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/${DB_NAME:managementpatients}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:secret}
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    format: false
  data:
    web:
      pageable:
        page-parameter: page
        size-parameter: limit
      sort:
        sort-parameter: sort

server:
  error:
    include-stacktrace: never
  port: 9090

api:
  security:
    token:
      secret: ${JWT_SECRET:123456789}