spring:
  application:
    name: api
  datasource:
    url: jdbc:postgresql://localhost:5432/managementpatients
    username: postgres
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
